'use strict';
// Tier 2 of the measured-savings spec: the BPE tokenizer that replaced
// `Math.ceil(str.length / 4)`, and the CALIBRATION that justifies it.
//
// This suite is a measuring instrument as much as a regression test. Half of
// it pins behaviour; the other half re-derives, from this repo's own source on
// every run, the error figures quoted in lib/token-estimate.js's header and in
// the audit. Numbers in a commit message rot. Numbers a suite recomputes and
// asserts bands around do not.
//
// WHAT "CORRECT" MEANS HERE, precisely, because it is easy to overclaim:
//
//  1. The merge loop is EXACT with respect to the vendored vocabulary. Its
//     output equals tiktoken's reference implementation for every fixture in
//     fixtures/bpe-reference-counts.json, which was generated by that
//     implementation. This is a real, checkable claim and it is what makes the
//     estimator deterministic.
//  2. The vocabulary is an APPROXIMATION of Claude's current tokenizer. It is
//     the last Claude-family vocabulary Anthropic published; current models do
//     not use it. No test here asserts agreement with Claude's billing,
//     because no such agreement is available offline -- see the ceiling
//     measured in the audit, where every real tokenizer, this one included,
//     lands 30-35% under the vendor-reported counts on real transcripts.
//
// Run via `node test/run.js token-estimate`, or this file directly.
const h = require('../harness'); // FIRST: pins MEMBRIDGE_* env before any lib require
const { check } = h;
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const REPO = path.join(__dirname, '..', '..');
const te = require('../../lib/token-estimate');
const bpe = require('../../lib/bpe');

const fixtures = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'fixtures', 'bpe-reference-counts.json'), 'utf8'),
);

// --- 1. exactness against the reference implementation ----------------------

check('tokenizer: every fixture matches tiktoken\'s reference count exactly', () => {
  const wrong = [];
  for (const c of fixtures) {
    const got = te.estimateTokens(c.text);
    if (got !== c.tokens) wrong.push(`${c.name}: got ${got}, reference ${c.tokens}`);
  }
  assert.deepStrictEqual(wrong, [], 'the merge loop diverged from the reference implementation');
  assert.ok(fixtures.length >= 25, 'the fixture corpus must stay broad enough to be worth running');
});

check('tokenizer: multibyte text is counted in tokens, not in bytes or chars', () => {
  // The bias the spec names at lib/recall.js's MINOR 2. Japanese is the sharp
  // case: 20 characters, 60 bytes, and neither number is the token count.
  const jp = fixtures.find(c => c.name === 'japanese');
  const chars = jp.text.length;
  const bytes = Buffer.byteLength(jp.text, 'utf8');
  assert.ok(bytes > chars * 2, 'fixture must actually be multibyte for this to test anything');
  assert.strictEqual(te.estimateTokens(jp.text), jp.tokens);
  assert.notStrictEqual(jp.tokens, Math.ceil(chars / 4), 'chars/4 and the real count must differ here');
  assert.notStrictEqual(jp.tokens, Math.ceil(bytes / 4), 'bytes/4 and the real count must differ here');
});

check('tokenizer: deterministic across calls and across processes', () => {
  const sample = fixtures.find(c => c.name === 'lib/roi.js head');
  const a = te.estimateTokens(sample.text);
  const b = te.estimateTokens(sample.text);
  assert.strictEqual(a, b, 'two calls in one process must agree');
  const script = `const te = require(${JSON.stringify(path.join(REPO, 'lib', 'token-estimate.js'))});
    process.stdout.write(String(te.estimateTokens(${JSON.stringify(sample.text)})));`;
  const out = spawnSync(process.execPath, ['-e', script], { encoding: 'utf8' });
  assert.strictEqual(out.status, 0, out.stderr);
  assert.strictEqual(Number(out.stdout), a, 'a fresh process must produce the same count');
});

// --- 2. calibration: how wrong was chars/4, measured on real source ---------

// The corpus is this repo's own lib/, which is what recall actually prices.
const corpus = fs.readdirSync(path.join(REPO, 'lib'))
  .filter(f => f.endsWith('.js'))
  .map(f => fs.readFileSync(path.join(REPO, 'lib', f), 'utf8'));

check('calibration: chars/4 is not centred, and the real ratio is measured not assumed', () => {
  let chars = 0;
  let tokens = 0;
  for (const src of corpus) {
    chars += src.length;
    tokens += te.estimateTokens(src);
  }
  const ratio = chars / tokens;
  const chars4Error = ((chars / 4) - tokens) / tokens;
  console.log(`  corpus: ${corpus.length} files, ${chars} chars, ${tokens} tokens`);
  console.log(`  measured chars-per-token: ${ratio.toFixed(3)} (chars/4 assumes 4.000)`);
  console.log(`  chars/4 aggregate error vs BPE: ${(100 * chars4Error).toFixed(2)}%`);
  // A band, not a point: the corpus changes as the repo does. The claim being
  // pinned is that the real ratio is meaningfully below 4, which is what makes
  // chars/4 a biased estimator of source code rather than a noisy one.
  assert.ok(ratio > 3.2 && ratio < 3.95, `chars-per-token ${ratio.toFixed(3)} left the expected band`);
  assert.ok(chars4Error < -0.02, 'chars/4 must still be measurably understating this corpus');
});

check('calibration: chars/4 error is per-file and does not cancel', () => {
  // The reason a corpus-level ratio is not the whole story: if the error were
  // uniform it could be corrected with one constant. It is not -- it varies by
  // file, so any single-divisor estimator is wrong file by file.
  const errs = corpus.map(src => {
    const t = te.estimateTokens(src);
    return t > 0 ? ((Math.ceil(src.length / 4) - t) / t) : 0;
  }).sort((a, b) => a - b);
  const q = p => errs[Math.floor(errs.length * p)];
  const meanAbs = errs.reduce((a, e) => a + Math.abs(e), 0) / errs.length;
  console.log(`  chars/4 per-file error: min ${(100 * errs[0]).toFixed(1)}%, p10 ${(100 * q(0.1)).toFixed(1)}%, `
    + `median ${(100 * q(0.5)).toFixed(1)}%, p90 ${(100 * q(0.9)).toFixed(1)}%, max ${(100 * errs[errs.length - 1]).toFixed(1)}%`);
  console.log(`  chars/4 mean absolute per-file error: ${(100 * meanAbs).toFixed(2)}%`);
  const spread = errs[errs.length - 1] - errs[0];
  assert.ok(spread > 0.1, `per-file error spread ${(100 * spread).toFixed(1)}% is too small to be the documented one`);
  assert.ok(meanAbs > 0.02, 'chars/4 must still be measurably wrong per file');
});

check('calibration: the stat-only constants are consistent with the tokenizer they stand in for', () => {
  // BYTES_PER_TOKEN and TOKENS_PER_LINE price a read that is not in hand. They
  // cannot be exact, but they must not drift away from the tokenizer they
  // approximate -- that drift is precisely what made the old bytes/4-vs-chars/4
  // pair incomparable.
  let bytes = 0;
  let lines = 0;
  let tokens = 0;
  for (const src of corpus) {
    bytes += Buffer.byteLength(src, 'utf8');
    lines += src.split('\n').length;
    tokens += te.estimateTokens(src);
  }
  const measuredBpt = bytes / tokens;
  const measuredTpl = tokens / lines;
  console.log(`  measured bytes-per-token ${measuredBpt.toFixed(3)} vs constant ${te.BYTES_PER_TOKEN}`);
  console.log(`  measured tokens-per-line ${measuredTpl.toFixed(2)} vs constant ${te.TOKENS_PER_LINE}`);
  assert.ok(Math.abs(measuredBpt - te.BYTES_PER_TOKEN) / measuredBpt < 0.1,
    `BYTES_PER_TOKEN drifted more than 10% from the measured ratio (${measuredBpt.toFixed(3)})`);
  assert.ok(Math.abs(measuredTpl - te.TOKENS_PER_LINE) / measuredTpl < 0.15,
    `TOKENS_PER_LINE drifted more than 15% from the measured ratio (${measuredTpl.toFixed(2)})`);
  // The old constants, for the record: both understated, in the same direction.
  assert.ok(measuredBpt < 4, 'bytes/4 overstated bytes per token, so it understated the read');
  assert.ok(measuredTpl > 12, 'lines*12 understated tokens per line');
});

// --- 3. degradation: a missing vocabulary must never break anything ---------

check('tokenizer: a missing vocabulary falls back to chars/4 and says it is degraded', () => {
  // A child process, because the vocabulary path is resolved once per process
  // exactly like lib/skeleton.js's grammar dir.
  const script = `
    process.env.MEMBRIDGE_TOKENIZER_VOCAB = ${JSON.stringify(path.join(REPO, 'vendor', 'tokenizer', 'does-not-exist.json'))};
    const te = require(${JSON.stringify(path.join(REPO, 'lib', 'token-estimate.js'))});
    const n = te.estimateTokens('hello world, this is a fallback');
    process.stdout.write(JSON.stringify({ n, info: te.tokenizerInfo() }));`;
  const out = spawnSync(process.execPath, ['-e', script], { encoding: 'utf8' });
  assert.strictEqual(out.status, 0, `a missing vocabulary must never throw: ${out.stderr}`);
  const res = JSON.parse(out.stdout);
  assert.strictEqual(res.n, Math.ceil('hello world, this is a fallback'.length / 4),
    'the fallback must be exactly the old chars/4 heuristic');
  assert.strictEqual(res.info.degraded, true);
  assert.strictEqual(res.info.method, 'chars4');
  assert.strictEqual(res.info.vocabulary, null);
  assert.strictEqual(res.info.kind, 'estimate', 'degraded or not, it is an estimate');
});

check('tokenizer: a malformed vocabulary degrades the same way', () => {
  const bad = path.join(h.ROOT, 'broken-vocab.json');
  fs.writeFileSync(bad, '{"bpe_ranks": 12, "pat_str": null}');
  const script = `
    process.env.MEMBRIDGE_TOKENIZER_VOCAB = ${JSON.stringify(bad)};
    const te = require(${JSON.stringify(path.join(REPO, 'lib', 'token-estimate.js'))});
    process.stdout.write(JSON.stringify({ n: te.estimateTokens('abcd'), info: te.tokenizerInfo() }));`;
  const out = spawnSync(process.execPath, ['-e', script], { encoding: 'utf8' });
  assert.strictEqual(out.status, 0, out.stderr);
  const res = JSON.parse(out.stdout);
  assert.strictEqual(res.n, 1);
  assert.strictEqual(res.info.degraded, true);
});

check('tokenizer: MEMBRIDGE_NO_BPE=1 restores the old heuristic without touching the vocabulary', () => {
  const script = `
    process.env.MEMBRIDGE_NO_BPE = '1';
    const te = require(${JSON.stringify(path.join(REPO, 'lib', 'token-estimate.js'))});
    const bpe = require(${JSON.stringify(path.join(REPO, 'lib', 'bpe.js'))});
    const n = te.estimateTokens('日本語のテキスト');
    process.stdout.write(JSON.stringify({ n, state: bpe.vocabularyState(), info: te.tokenizerInfo() }));`;
  const out = spawnSync(process.execPath, ['-e', script], { encoding: 'utf8' });
  assert.strictEqual(out.status, 0, out.stderr);
  const res = JSON.parse(out.stdout);
  assert.strictEqual(res.n, Math.ceil('日本語のテキスト'.length / 4));
  assert.strictEqual(res.state, 'unloaded', 'the kill switch must not pay the vocabulary load');
  assert.strictEqual(res.info.method, 'chars4');
});

check('tokenizer: junk input never throws', () => {
  for (const junk of [null, undefined, 0, NaN, {}, [], true, Symbol.iterator.toString()]) {
    assert.doesNotThrow(() => te.estimateTokens(junk), `threw on ${String(junk)}`);
    assert.ok(Number.isFinite(te.estimateTokens(junk)));
  }
  assert.strictEqual(te.estimateTokens(''), 0);
  assert.strictEqual(te.estimateTokensFromBytes(-5), 0);
  assert.strictEqual(te.estimateTokensFromLines('nonsense'), 0);
});

// --- 4. the startup-cost invariants this module exists to protect -----------

check('tokenizer: requiring the recall hot path pulls in neither tree-sitter NOR the vocabulary', () => {
  // The first half is the existing require-cache invariant (test/run-tests.js
  // pins it too, and it must keep passing). The second half is new and is the
  // reason the vocabulary is lazily read: requiring the hook must not cost a
  // 681 KB parse for a call that may never count a token.
  const script = `require(${JSON.stringify(path.join(REPO, 'lib', 'hooks-recall.js'))});
    const bpe = require(${JSON.stringify(path.join(REPO, 'lib', 'bpe.js'))});
    console.log(JSON.stringify({
      treeSitter: Object.keys(require.cache).filter(k => /tree-sitter/.test(k)),
      vocab: bpe.vocabularyState(),
    }));`;
  const out = spawnSync(process.execPath, ['-e', script], { encoding: 'utf8' });
  assert.strictEqual(out.status, 0, out.stderr);
  const res = JSON.parse(out.stdout.trim());
  assert.deepStrictEqual(res.treeSitter, [], 'the recall hot path loaded a parser at require time');
  assert.strictEqual(res.vocab, 'unloaded', 'the recall hot path loaded the vocabulary at require time');
});

check('tokenizer: the vocabulary loads once per process, and the load is bounded', () => {
  const script = `
    const bpe = require(${JSON.stringify(path.join(REPO, 'lib', 'bpe.js'))});
    const t0 = process.hrtime.bigint();
    bpe.countTokens('warm the vocabulary');
    const loadMs = Number(process.hrtime.bigint() - t0) / 1e6;
    const t1 = process.hrtime.bigint();
    for (let i = 0; i < 200; i++) bpe.countTokens('a moderately typical line of source code');
    const warmMs = Number(process.hrtime.bigint() - t1) / 1e6 / 200;
    process.stdout.write(JSON.stringify({ loadMs, warmMs }));`;
  const out = spawnSync(process.execPath, ['-e', script], { encoding: 'utf8' });
  assert.strictEqual(out.status, 0, out.stderr);
  const { loadMs, warmMs } = JSON.parse(out.stdout);
  console.log(`  first count (incl. vocabulary load): ${loadMs.toFixed(1)}ms; warm count: ${warmMs.toFixed(3)}ms`);
  // Generous ceilings -- this is a hot path but the suite may share a busy
  // machine, and a wall-clock assertion is only here to catch an order-of-
  // magnitude regression (a per-call reload, a lost cache), not to benchmark.
  assert.ok(loadMs < 500, `vocabulary load took ${loadMs.toFixed(1)}ms`);
  assert.ok(warmMs < 5, `warm count took ${warmMs.toFixed(3)}ms -- the vocabulary may be reloading per call`);
});

check('tokenizer: a pathological single token run stays bounded', () => {
  // MAX_PIECE_BYTES. A 200 KB unbroken punctuation run is the shape that makes
  // an unchunked O(n^2) merge loop hang a hook.
  const nasty = '!'.repeat(200000);
  const t0 = Date.now();
  const n = te.estimateTokens(nasty);
  const ms = Date.now() - t0;
  console.log(`  200k-char punctuation run: ${n} tokens in ${ms}ms`);
  assert.ok(n > 0);
  assert.ok(ms < 5000, `chunking failed: ${ms}ms`);
});

// --- 5. the honesty invariant ----------------------------------------------

check('tokenizer: nothing it reports ever claims to be measured', () => {
  const info = te.tokenizerInfo();
  assert.strictEqual(info.kind, 'estimate');
  assert.ok(!/measured/i.test(JSON.stringify(info)),
    'the tokenizer payload must never carry the word "measured" -- the only measured token '
    + 'figures MemBridge has are vendor-reported');
  const src = fs.readFileSync(path.join(REPO, 'lib', 'token-estimate.js'), 'utf8');
  assert.ok(/STILL AN ESTIMATE/.test(src), 'the module must keep saying so in its own header');
});

h.finish();
